### ISSUE TITLE
Could you tell me How it can run SpaceInvadersNoFrameskip-v4?

### ISSUE THREAD

**Issue by THSWind** [k4ntz/SPACE#1]

**Comment by k4ntz** [comment]
What do you mean by "run", is it that you want to use a trained MOC object detection program for inference or train one ?

**Comment by THSWind** [comment]
Does your program can run "SpaceInvadersNoFrameskip-v4"(an environment of atari 2600), I want to  see the result of this game about how it's reward curve like, etc.

Thank you so much for reply

**Comment by k4ntz** [comment]
MOC is an object detection algorithm. You need to use it inside a reinforcement learning algorithm if you want to observe the reward curve. I can provide you a script that does that on Pong, and we can try to adapt it to space invaders to see if an agent that first uses MOC to detect object and then use these objects for finding the policy works.

**Comment by THSWind** [comment]
oh， thank you very much. I have no question now.



---- Replied Message ----
| From | ***@***.***> |
| Date | 01/09/2023 18:42 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [k4ntz/MOC] Could you tell me How it can run SpaceInvadersNoFrameskip-v4? (Issue #1) |

MOC is an object detection algorithm. You need to use it inside a reinforcement learning algorithm if you want to observe the reward curve. I can provide you a script that does that on Pong, and we can try to adapt it to space invaders to see if an agent that first uses MOC to detect object and then use these objects for finding the policy works.
